Docs en su propia carpeta
StartForKillerMC/plataforma-back-end pull request #5
Opened 2022-09-04 01:50 UTC by beto-bit

Se movieron los docs a su propia carpeta (ahora para acceder a la documentación local se usa el archivo /docs/docs.html). Removidos imports sin utilizar.

2022-09-04 12:01 UTC, StartForKillerMC requested changes
No entendiste lo del index.html, no te dije cambiarlo de carpeta, tiene que estar en la raíz para funcionar, te dije que dentro de él cambiases la ruta a API.json

2022-09-05 00:08 UTC, beto-bit commented
Estuve testeando los docs dentro de la carpeta y aparentemente (sirviéndolos desde un servidor http simple con Python) funcionaban bien dentro de la carpeta. En caso se muevan los docs a la carpeta, voy a cerrar la pull request y descartar el commit para eliminar los conflictos de mi fork.

2022-09-05 00:08 UTC, closed without merging

2022-09-05 01:30 UTC, StartForKillerMC commented
Pero una cosa, no estaba mal la idea, simplemente lo que te decía es que dentro de el index.html cambiases el api.json a docs/api.json

2022-09-05 03:23 UTC, beto-bit commented
Ya, me parecía conveniente mover el `index.html` a `docs/` para que estuviese un poco mejor organizado.